name: Deploy .NET API to Azure

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.101" # Use your version

      - name: Restore
        run: dotnet restore ./backend/IntexS3G2.API/IntexS3G2.csproj

      - name: Clean
        run: dotnet clean ./backend/IntexS3G2.API/IntexS3G2.csproj

      - name: Build
        run: dotnet build ./backend/IntexS3G2.API/IntexS3G2.csproj --configuration Release

      - name: Publish
        run: dotnet publish ./backend/IntexS3G2.API/IntexS3G2.csproj --configuration Release --output ./publish

      - name: Inject connection string for Identity
        run: echo "IdentityConnection=${{ secrets.IDENTITY_CONNECTION }}" >> $GITHUB_ENV

      - name: Inject connection string for Movie
        run: echo "MovieConnection=${{ secrets.MOVIE_CONNECTION }}" >> $GITHUB_ENV
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "IntexS3G2-Backend"
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./publish
