name: Deploy .NET API to Azure

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.101" # Use your version

      - name: Restore
        run: dotnet restore ./backend/IntexS3G2.API

      - name: Build
        run: dotnet build ./backend/IntexS3G2.API --configuration Release

      - name: Publish
        run: dotnet publish ./backend/IntexS3G2.API --configuration Release --output ./backend/IntexS3G2.API/publish

      - name: Replace DB password in appsettings.json
        run: |
          sed -i 's/__AUTH_DB_PASSWORD__/${{ secrets.AUTH_DB_PASSWORD }}/g' ./backend/IntexS3G2.API/appsettings.json

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "IntexS3G2-Backend"
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./backend/IntexS3G2.API/publish
